drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists operation;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop sequence compte_seq;
drop sequence operation_seq;
